[package]
name = "rend3-egui-example"
license = "MIT OR Apache-2.0 OR Zlib"
version = "0.1.0"
authors = ["Juri Furer <juri.furer@protonmail.com>"]
edition = "2021"
publish = false

[[bin]]
name = "egui"
path = "src/main.rs"

[dependencies]
# The egui immediate mode gui library
egui = "0.15.0"
# Backend-agnostic interface for writing apps using egui
epi = "0.15.0"
# Winit integration with egui
egui_winit_platform = { version = "0.11.0", git = "https://github.com/cwfitzgerald/egui_winit_platform.git", rev = "eaef13fd5d70bb5b3251424711012ceedb71994b" }
# logging
env_logger = { version = "0.9", default-features = false, features = ["termcolor", "atty"] }
# Linear algebra library
glam = "0.20"
# Provides `block_on` to wait for futures from sync code
pollster = "0.2"
# Renderer core
rend3 = { version = "^0.2.0",path = "../../rend3" }
# Egui renderer integration
rend3-egui = { version = "^0.1.0",path = "../../rend3-egui" }
# Programmable render list that dictates how the scene renders
rend3-pbr = { version = "^0.2.0",path = "../../rend3-pbr" }
# Windowing
winit = "0.25.0"
