[package]
name = "rend3-egui"
version = "0.2.0"
authors = ["The rend3 Developers"]
edition = "2021"
description = "Egui Render Routine for rend3"
readme = "../README.md"
license = "MIT OR Apache-2.0 OR Zlib"
repository = "https://github.com/BVE-Reborn/rend3"
keywords = ["3d", "graphics", "gpu", "renderer", "wgpu"]
categories = ["game-development", "graphics", "rendering", "rendering::engine"]

[dependencies]
egui = "0.15.0"
egui_wgpu_backend = { version = "0.14.0", git = "https://github.com/hasenbanck/egui_wgpu_backend.git", rev = "925a4564ea7608eba0333bd9a2521567b68b717a" }
epi = "0.15.0"
glam = "0.20.0"
rend3 = { version = "^0.2.0", path = "../rend3" }
wgpu = "0.11"
