[package]
authors = ["The rend3 Developers"]
categories = ["game-development", "graphics", "rendering", "rendering::engine"]
description = "Egui Render Routine for rend3"
edition = "2021"
keywords = ["3d", "graphics", "gpu", "renderer", "wgpu"]
license = "MIT OR Apache-2.0 OR Zlib"
name = "rend3-egui"
readme = "../README.md"
repository = "https://github.com/BVE-Reborn/rend3"
version = "0.1.0"

[dependencies]
egui = "0.15"
epi = "0.15"
egui_wgpu_backend = "0.14"
rend3 = { version = "^0.2.0", path = "../rend3" }
wgpu = "0.11"
flume = "0.10"
glam = "0.20"
