[package]
name = "rend3"
version = "0.0.5"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
description = "Easy to use, customizable, efficient 3D renderer library built on wgpu."
readme = "../README.md"
repository = "https://github.com/BVE-Reborn/rend3"
license = "MIT OR Apache-2.0 OR Zlib"
keywords = ["3d", "graphics", "gpu", "renderer", "wgpu"]
categories = ["game-development", "graphics", "rendering", "rendering::engine"]

[package.metadata.release]
disable-tag = false
tag-prefix = ""
pre-release-hook = ["cargo", "readme", "-o", "../README.md", "-t", "../README.tpl"]
[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "rend3 = \"[a-z0-9\\.-]+\""
replace = "rend3 = \"{{version}}\""
[[package.metadata.release.pre-release-replacements]]
file = "../CHANGELOG.md"
search = "\\[Unreleased\\]\\(#unreleased\\)"
replace = "[Unreleased](#unreleased)\n- [v{{version}}](#v{{version}})"
[[package.metadata.release.pre-release-replacements]]
file = "../CHANGELOG.md"
search = "\\[v([0-9+])\\.([0-9+])\\.([0-9+])\\]\\(#v[0-9\\.]+\\)"
replace = "[v$1.$2.$3](#v$1$2$3)"
[[package.metadata.release.pre-release-replacements]]
file = "../CHANGELOG.md"
search = "## Unreleased"
replace = "## Unreleased\n\n## v{{version}}\n\nReleased {{date}}"
[[package.metadata.release.pre-release-replacements]]
file = "../CHANGELOG.md"
search = "\\[Unreleased\\]\\(https://github.com/BVE-Reborn/rend3/compare/v([a-z0-9.-]+)\\.\\.\\.HEAD\\)"
replace = "[Unreleased](https://github.com/BVE-Reborn/rend3/compare/v{{version}}...HEAD)\n- [v{{version}}](https://github.com/BVE-Reborn/rend3/compare/v$1...v{{version}})"

[dependencies]
arrayvec = "0.7"
bitflags = "1"
bytemuck = "1"
glam = { version = "0.16", features = ["bytemuck"] }
include_dir = "0.6"
indexmap = "1"
itertools = "0.10"
flume = "0.10"
fnv = "1"
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
futures-intrusive = "0.4"
parking_lot = { version = "0.11", features = ["send_guard"] }
path-dedot = "3"
raw-window-handle = "0.3"
range-alloc = "0.1"
shaderc = "0.7.2"
smallvec = "1"
switchyard = "0.2"
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-futures = "0.2"
thiserror = "1"
wgpu = "0.7"
wgpu-conveyor = "0.2"
