[package]
name = "rend3"
version = "0.1.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
description = "Asynchronous renderer made for capstone"
readme = "README.md"
repository = "https://github.com/cwfitzgerald/capstone"
license = "MPL-2.0"
keywords = []
categories = []

[dependencies]
bitflags = "1"
bytemuck = "1"
glam = "0.9"
imgui = "0.4"
imgui-wgpu = "0.9"
indexmap = "1"
fnv = "1"
futures = { version = "0.3", default-features = false }
futures-intrusive = "0.3"
parking_lot = { version = "0.11", features = ["send_guard"] }
raw-window-handle = "0.3"
range-alloc = "0.1"
shaderc = "0.6"
smallvec = "1"
switchyard = { version = "0.1", git = "https://github.com/BVE-Reborn/switchyard.git", rev = "5190d15689dfcb9896880087384c0a01c7f18290" }
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-futures = "0.2"
thiserror = "1"
wgpu = "0.6"
wgpu-conveyor = { version = "0.1", git = "https://github.com/BVE-Reborn/wgpu-conveyor.git", rev = "380d8bc8a74abc684b8c0a21a7987fe505c84d19" }
winit = { git = "https://github.com/rust-windowing/winit.git", rev = "c1ea0dde92e1de9e029e7fbb2485a454aa81b918",  default-features = false, features = ["x11"] }
