[package]
name = "rend3"
version = "0.1.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
description = "Asynchronous renderer made for capstone"
readme = "README.md"
repository = "https://github.com/cwfitzgerald/capstone"
license = "MPL-2.0"
keywords = []
categories = []

[dependencies]
arrayvec = "0.5"
bitflags = "1"
bytemuck = "1"
glam = "0.10"
imgui = "0.6"
#imgui-wgpu = "0.9"
include_dir = "0.6"
indexmap = "1"
itertools = "0.9"
flume = "0.9"
fnv = "1"
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
futures-intrusive = "0.4"
parking_lot = { version = "0.11", features = ["send_guard"] }
path-dedot = "3"
raw-window-handle = "0.3"
range-alloc = "0.1"
shaderc = "0.7"
smallvec = "1"
switchyard = "0.1"
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-futures = "0.2"
thiserror = "1"
wgpu = { version = "0.6", features = ["trace"] }
wgpu-conveyor = { version = "0.1", git = "https://github.com/BVE-Reborn/wgpu-conveyor.git", rev = "380d8bc8a74abc684b8c0a21a7987fe505c84d19" }
winit = { version = "0.23",  default-features = false }
