[package]
name = "rend3-gltf"
version = "0.0.5"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
description = "gltf scene and model loader for rend3"
repository = "https://github.com/BVE-Reborn/rend3"
license = "MIT OR Apache-2.0 OR Zlib"
keywords = ["3d", "graphics", "gltf", "loading", "rend3"]
categories = ["game-development", "graphics", "parser-implementations", "rendering", "rendering::engine"]

[dependencies]
async-std = "1"
gltf = { version = "0.16", features = ["KHR_lights_punctual", "KHR_materials_unlit", "extras", "names", "utils"] }
glam = "0.17"
futures-util = "0.3"
fnv = "1"
image = "0.23"
rend3 = { version = "^0.0.5", path = "../rend3" }
thiserror = "1"
