[package]
name = "rend3-imgui-example"
license = "MIT OR Apache-2.0 OR Zlib"
version = "0.1.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"

[[bin]]
name = "imgui"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Linear algebra library
glam = "0.12"
# Renderer
rend3 = { path = "../../rend3", version = "0.1.0" }
rend3-list = { path = "../../rend3-list", version = "0.1.0" }
# imgui and integrations
imgui = "0.6"
imgui-winit-support = "0.6"
imgui-wgpu = { version = "0.12", git = "https://github.com/cwfitzgerald/imgui-wgpu-rs.git", rev = "3967763d077f40834cae28f3aa0ef2acfd6e039c" }
# Provides `block_on` to wait for futures from sync code
pollster = "0.2"
# core rendering api used by rend3 etc
wgpu = { version = "0.6", git = "https://github.com/gfx-rs/wgpu-rs", rev = "f882abcf4b3d1e9bfbfc95b61874344661956479" }
# wgpu-aware logging
wgpu-subscriber = "0.1"
# windowing
winit = "0.24"
